'use client';

import React, { useState } from 'react';
import { Card } from '../../ui/card';
import { Button } from '../../ui/button';
import { Copy, Check, Download, FileText } from 'lucide-react';

export const RobotsGenerator: React.FC = () => {
  const [sitemapUrl, setSitemapUrl] = useState('https://Numvax.com/sitemap.xml');
  const [allowAll, setAllowAll] = useState(true);
  const [disallowAdmin, setDisallowAdmin] = useState(true);
  const [disallowApi, setDisallowApi] = useState(true);
  const [crawlDelay, setCrawlDelay] = useState<number | ''>('');

  const generateRobots = () => {
    let lines = ['# Robots.txt generated by Numvax (https://Numvax.com)', 'User-agent: *'];
    if (allowAll) {
      lines.push('Allow: /');
    }
    if (disallowAdmin) {
      lines.push('Disallow: /admin');
      lines.push('Disallow: /admin/*');
    }
    if (disallowApi) {
      lines.push('Disallow: /api/');
    }
    if (crawlDelay) {
      lines.push(`Crawl-delay: ${crawlDelay}`);
    }
    if (sitemapUrl.trim()) {
      lines.push(`\nSitemap: ${sitemapUrl.trim()}`);
    }
    return lines.join('\n');
  };

  const output = generateRobots();

  const [copied, setCopied] = useState(false);
  const copyOutput = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    a.click();
  };

  return (
    <Card>
      <div className="flex flex-col gap-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="flex flex-col gap-3">
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-semibold text-neutral-700">Sitemap URL:</label>
              <input
                type="url"
                value={sitemapUrl}
                onChange={(e) => setSitemapUrl(e.target.value)}
                placeholder="https://yourdomain.com/sitemap.xml"
                className="w-full px-3 py-2 text-xs bg-white border border-neutral-300 rounded-xl text-neutral-900 focus:outline-none"
              />
            </div>

            <div className="flex flex-col gap-2 pt-2">
              <label className="flex items-center gap-2 text-xs text-neutral-800 cursor-pointer">
                <input type="checkbox" checked={allowAll} onChange={(e) => setAllowAll(e.target.checked)} className="rounded" />
                Allow all search crawlers by default (Allow: /)
              </label>
              <label className="flex items-center gap-2 text-xs text-neutral-800 cursor-pointer">
                <input type="checkbox" checked={disallowAdmin} onChange={(e) => setDisallowAdmin(e.target.checked)} className="rounded" />
                Disallow admin directory (/admin)
              </label>
              <label className="flex items-center gap-2 text-xs text-neutral-800 cursor-pointer">
                <input type="checkbox" checked={disallowApi} onChange={(e) => setDisallowApi(e.target.checked)} className="rounded" />
                Disallow API endpoints (/api/)
              </label>
            </div>
          </div>

          <div className="flex flex-col gap-1.5">
            <div className="flex items-center justify-between">
              <label className="text-xs font-semibold text-neutral-700">Generated Robots.txt:</label>
              <div className="flex items-center gap-2">
                <button onClick={copyOutput} className="text-xs text-neutral-600 hover:text-neutral-900 flex items-center gap-1">
                  {copied ? <Check className="w-3 h-3 text-emerald-600" /> : <Copy className="w-3 h-3" />}
                  {copied ? 'Copied' : 'Copy'}
                </button>
                <button onClick={downloadFile} className="text-xs text-neutral-600 hover:text-neutral-900 flex items-center gap-1">
                  <Download className="w-3 h-3" /> Download
                </button>
              </div>
            </div>
            <textarea
              value={output}
              readOnly
              rows={8}
              className="w-full p-3 bg-neutral-900 text-neutral-100 font-mono text-xs rounded-xl border border-neutral-800 focus:outline-none"
            />
          </div>
        </div>
      </div>
    </Card>
  );
};
