import React from 'react';
import { Metadata } from 'next';
import { Breadcrumb } from '@/components/navigation/Breadcrumb';

export const metadata: Metadata = {
  title: 'Disclaimer - Numvax',
  description: 'Numvax accuracy disclaimer and general usage terms.',
  alternates: {
    canonical: 'https://Numvax.com/disclaimer',
  },
};

export default function DisclaimerPage() {
  const breadcrumbs = [
    { name: 'Home', url: 'https://Numvax.com' },
    { name: 'Disclaimer', url: 'https://Numvax.com/disclaimer' },
  ];

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 flex flex-col gap-6">
      <Breadcrumb items={breadcrumbs} />

      <h1 className="text-3xl font-extrabold text-neutral-900 tracking-tight">
        Disclaimer
      </h1>

      <div className="bg-white border border-neutral-200 rounded-2xl p-6 flex flex-col gap-4 leading-relaxed text-sm text-neutral-600">
        <h2 className="text-base font-bold text-neutral-900">General Disclaimer</h2>
        <p>
          Numvax strives to ensure that all calculations and information provided on this platform are accurate and up-to-date. However, results generated by our online calculators are intended solely for educational, planning, and estimation purposes.
        </p>

        <h2 className="text-base font-bold text-neutral-900">Financial & Medical Disclaimers</h2>
        <p>
          - <strong>Financial Tools (Loans & Discounts):</strong> Loan amortization schedules and payment calculations are estimates. Actual interest charges, fees, taxes, and loan terms are determined by your financial institution.
        </p>
        <p>
          - <strong>Health Tools (BMI):</strong> Body Mass Index (BMI) calculations are statistical screening estimates and do not constitute a medical diagnosis. Consult a healthcare provider for personalized medical advice.
        </p>
      </div>
    </div>
  );
}
